version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-api
    ports:
      - "3005:3005"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:prod
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
